import '../models/models.dart';

/// Complete Vedic astrology data constants
class AstroData {
  // ═══════════════════════════════════════════════════════════════
  // PLANETS (Grahas)
  // ═══════════════════════════════════════════════════════════════
  
  static const List<Planet> planets = [
    Planet(
      id: 'sun',
      name: 'Sun',
      sanskritName: 'Surya',
      symbol: '☉',
      karakas: [
        'Soul & self-identity',
        'Father & authority figures',
        'Government & leadership',
        'Health & vitality',
        'Fame & recognition',
        'Willpower & confidence',
      ],
      naturalRole: 'King - The soul\'s expression and life force',
      functionalRole: 'Varies by ascendant - represents authority, ego, and self-expression',
      psychologicalTendencies: [
        'Strong sense of self and identity',
        'Natural leadership qualities',
        'Desire for recognition and respect',
        'Pride and dignity in actions',
        'Need for creative self-expression',
      ],
      dailyBehaviors: [
        'How you present yourself to the world',
        'Your relationship with authority',
        'Your level of confidence in decisions',
        'How you seek and handle recognition',
        'Your vitality and energy levels',
      ],
      strengtheningActions: [
        'Wake up early and greet the sunrise',
        'Practice leadership in small daily decisions',
        'Develop a strong morning routine',
        'Build confidence through competence',
        'Respect and honor father figures',
        'Take responsibility for your actions',
      ],
      observationPrompts: [
        'When do you feel most confident and alive?',
        'How do you react when your authority is challenged?',
        'What makes you feel truly recognized?',
      ],
      journalPrompt: 'Today I felt most like my authentic self when...',
      element: 'Fire',
      nature: 'Malefic (Krura)',
    ),
    Planet(
      id: 'moon',
      name: 'Moon',
      sanskritName: 'Chandra',
      symbol: '☽',
      karakas: [
        'Mind & emotions',
        'Mother & nurturing',
        'Mental peace & comfort',
        'Public & masses',
        'Memory & intuition',
        'Home & feelings of security',
      ],
      naturalRole: 'Queen - The mind\'s fluctuations and emotional nature',
      functionalRole: 'Determines mental makeup and emotional responses',
      psychologicalTendencies: [
        'Emotional sensitivity and fluctuations',
        'Strong intuitive abilities',
        'Need for emotional security',
        'Nurturing and caregiving tendencies',
        'Attachment to comfort and familiarity',
      ],
      dailyBehaviors: [
        'Your mood patterns throughout the day',
        'How you seek emotional comfort',
        'Your reaction to stress and change',
        'How you nurture yourself and others',
        'Your sleep patterns and rest needs',
      ],
      strengtheningActions: [
        'Practice mindfulness meditation daily',
        'Maintain emotional connections with loved ones',
        'Create a calming home environment',
        'Honor and respect your mother',
        'Track your emotional patterns',
        'Practice gratitude before sleep',
      ],
      observationPrompts: [
        'What triggers your strongest emotional responses?',
        'Where do you feel most emotionally safe?',
        'How do your moods change with the lunar cycle?',
      ],
      journalPrompt: 'My emotional state today was influenced by...',
      element: 'Water',
      nature: 'Benefic (Saumya)',
    ),
    Planet(
      id: 'mars',
      name: 'Mars',
      sanskritName: 'Mangal',
      symbol: '♂',
      karakas: [
        'Energy & action',
        'Courage & aggression',
        'Siblings & competitors',
        'Property & real estate',
        'Physical strength',
        'Technical skills & engineering',
      ],
      naturalRole: 'Commander - The warrior energy and drive to act',
      functionalRole: 'Indicates how you take action and handle conflict',
      psychologicalTendencies: [
        'Action-oriented mindset',
        'Competitive drive',
        'Quick temper but quick recovery',
        'Physical restlessness',
        'Desire for independence',
      ],
      dailyBehaviors: [
        'How you start and complete tasks',
        'Your reaction to obstacles',
        'Physical exercise patterns',
        'How you handle competition',
        'Your assertiveness in conversations',
      ],
      strengtheningActions: [
        'Regular physical exercise (especially strength training)',
        'Practice martial arts or competitive sports',
        'Take on challenging projects',
        'Learn technical or engineering skills',
        'Practice controlled aggression through discipline',
        'Support siblings and younger people',
      ],
      observationPrompts: [
        'What triggers your anger and how do you express it?',
        'When do you feel most energized to act?',
        'How do you handle competition?',
      ],
      journalPrompt: 'Today I channeled my energy effectively when...',
      element: 'Fire',
      nature: 'Malefic (Krura)',
    ),
    Planet(
      id: 'mercury',
      name: 'Mercury',
      sanskritName: 'Budha',
      symbol: '☿',
      karakas: [
        'Communication & speech',
        'Intelligence & analysis',
        'Learning & education',
        'Business & trade',
        'Writing & documentation',
        'Humor & playfulness',
      ],
      naturalRole: 'Prince - The intellect and communicative ability',
      functionalRole: 'Shows how you think, learn, and communicate',
      psychologicalTendencies: [
        'Curious and analytical mind',
        'Quick mental processing',
        'Love of learning and variety',
        'Playful and witty nature',
        'Tendency to overthink',
      ],
      dailyBehaviors: [
        'How you explain complex ideas',
        'Your learning and study style',
        'Problem-solving approaches',
        'Multitasking patterns',
        'Written and verbal communication',
      ],
      strengtheningActions: [
        'Read and study new subjects daily',
        'Practice clear written communication',
        'Learn a new language or skill',
        'Play word games and puzzles',
        'Journal your thoughts regularly',
        'Engage in debates and discussions',
      ],
      observationPrompts: [
        'How do you prefer to learn new information?',
        'When do you feel most intellectually engaged?',
        'Do you prefer details or the big picture first?',
      ],
      journalPrompt: 'When I need to communicate something important, I tend to...',
      element: 'Earth',
      nature: 'Benefic when alone, takes nature of conjunctions',
    ),
    Planet(
      id: 'jupiter',
      name: 'Jupiter',
      sanskritName: 'Guru',
      symbol: '♃',
      karakas: [
        'Wisdom & higher knowledge',
        'Teachers & mentors',
        'Luck & expansion',
        'Children & progeny',
        'Dharma & righteousness',
        'Wealth & prosperity',
      ],
      naturalRole: 'Minister - The great benefic and teacher',
      functionalRole: 'Indicates wisdom, growth, and blessings in life',
      psychologicalTendencies: [
        'Optimistic worldview',
        'Desire for meaning and purpose',
        'Generous and expansive nature',
        'Interest in philosophy and religion',
        'Teaching and mentoring inclinations',
      ],
      dailyBehaviors: [
        'How you seek meaning in experiences',
        'Your generosity with time and resources',
        'Attitude toward learning and growth',
        'How you guide and advise others',
        'Your faith in positive outcomes',
      ],
      strengtheningActions: [
        'Study philosophy, spirituality, or scriptures',
        'Mentor or teach someone',
        'Practice generosity without expectation',
        'Respect teachers and elders',
        'Maintain ethical integrity',
        'Expand your knowledge base regularly',
      ],
      observationPrompts: [
        'What gives your life the deepest meaning?',
        'How do you express gratitude?',
        'When do you feel most generous?',
      ],
      journalPrompt: 'Today I learned or taught something valuable about...',
      element: 'Ether/Space',
      nature: 'Benefic (Saumya)',
    ),
    Planet(
      id: 'venus',
      name: 'Venus',
      sanskritName: 'Shukra',
      symbol: '♀',
      karakas: [
        'Love & relationships',
        'Beauty & aesthetics',
        'Luxury & comforts',
        'Art & creativity',
        'Marriage & partnership',
        'Wealth & pleasures',
      ],
      naturalRole: 'Counselor - The planet of love, beauty, and harmony',
      functionalRole: 'Shows relationship patterns and aesthetic preferences',
      psychologicalTendencies: [
        'Appreciation for beauty and harmony',
        'Desire for love and connection',
        'Creative and artistic inclinations',
        'Pleasure-seeking nature',
        'Diplomatic and charming approach',
      ],
      dailyBehaviors: [
        'How you express affection',
        'Your aesthetic choices and style',
        'Approach to relationships',
        'How you seek comfort and pleasure',
        'Your creative expressions',
      ],
      strengtheningActions: [
        'Cultivate an appreciation for arts',
        'Practice kindness in relationships',
        'Create beauty in your environment',
        'Develop artistic skills',
        'Practice diplomacy and harmony',
        'Honor the feminine principle',
      ],
      observationPrompts: [
        'What kind of beauty moves you deeply?',
        'How do you show love to others?',
        'What brings you the most pleasure?',
      ],
      journalPrompt: 'I felt most connected to beauty and love when...',
      element: 'Water',
      nature: 'Benefic (Saumya)',
    ),
    Planet(
      id: 'saturn',
      name: 'Saturn',
      sanskritName: 'Shani',
      symbol: '♄',
      karakas: [
        'Discipline & structure',
        'Karma & consequences',
        'Time & delays',
        'Hard work & perseverance',
        'Servants & workers',
        'Old age & longevity',
      ],
      naturalRole: 'Servant - The taskmaster who teaches through limitation',
      functionalRole: 'Indicates areas of life requiring effort and patience',
      psychologicalTendencies: [
        'Serious and responsible approach',
        'Fear of failure or rejection',
        'Desire for structure and order',
        'Patience through adversity',
        'Focus on long-term goals',
      ],
      dailyBehaviors: [
        'How you handle responsibility',
        'Your relationship with time',
        'Approach to difficult tasks',
        'How you deal with limitations',
        'Your work ethic and discipline',
      ],
      strengtheningActions: [
        'Build consistent daily routines',
        'Practice patience in all things',
        'Serve those less fortunate',
        'Respect elders and workers',
        'Complete tasks you start',
        'Face fears with steady effort',
      ],
      observationPrompts: [
        'Where do you feel most restricted?',
        'How do you handle delays and setbacks?',
        'What responsibilities do you avoid?',
      ],
      journalPrompt: 'Today I demonstrated discipline and persistence by...',
      element: 'Air',
      nature: 'Malefic (Krura)',
    ),
    Planet(
      id: 'rahu',
      name: 'Rahu',
      sanskritName: 'Rahu',
      symbol: '☊',
      karakas: [
        'Obsession & desire',
        'Foreign elements',
        'Technology & innovation',
        'Illusion & confusion',
        'Amplification & excess',
        'Unconventional paths',
      ],
      naturalRole: 'Shadow planet - The north lunar node representing worldly desires',
      functionalRole: 'Shows areas of intense desire and karmic growth',
      psychologicalTendencies: [
        'Intense cravings and obsessions',
        'Attraction to the unusual',
        'Ambitious and driven nature',
        'Tendency toward excess',
        'Innovation and rule-breaking',
      ],
      dailyBehaviors: [
        'What you obsess over',
        'Your relationship with technology',
        'Tendency toward addictive behaviors',
        'How you chase worldly success',
        'Your fascination with the foreign',
      ],
      strengtheningActions: [
        'Channel obsessions into productive goals',
        'Practice moderation in desires',
        'Use technology mindfully',
        'Explore foreign cultures constructively',
        'Transform material goals into spiritual growth',
        'Avoid shortcuts and deception',
      ],
      observationPrompts: [
        'What do you obsess over most?',
        'Where do you seek shortcuts?',
        'What unconventional desires drive you?',
      ],
      journalPrompt: 'Today I noticed my strongest cravings were about...',
      element: 'Smoke/Air',
      nature: 'Malefic (Krura)',
    ),
    Planet(
      id: 'ketu',
      name: 'Ketu',
      sanskritName: 'Ketu',
      symbol: '☋',
      karakas: [
        'Spirituality & liberation',
        'Past life patterns',
        'Detachment & letting go',
        'Intuition & psychic ability',
        'Sudden events',
        'Healing & moksha',
      ],
      naturalRole: 'Shadow planet - The south lunar node representing past karma',
      functionalRole: 'Shows areas of natural talent and necessary detachment',
      psychologicalTendencies: [
        'Natural detachment from worldly matters',
        'Strong intuitive abilities',
        'Past-life skill carry-over',
        'Tendency toward isolation',
        'Spiritual seeking',
      ],
      dailyBehaviors: [
        'Areas where you feel naturally skilled',
        'What you easily let go of',
        'Your meditation and spiritual practices',
        'Intuitive decisions',
        'Moments of unexpected insight',
      ],
      strengtheningActions: [
        'Practice meditation regularly',
        'Develop spiritual understanding',
        'Let go of attachments gracefully',
        'Trust your intuition',
        'Use natural talents for service',
        'Embrace simplicity and minimalism',
      ],
      observationPrompts: [
        'What comes naturally to you without effort?',
        'What can you easily walk away from?',
        'When do you feel most spiritually connected?',
      ],
      journalPrompt: 'Today I experienced a moment of insight or detachment when...',
      element: 'Fire/Smoke',
      nature: 'Malefic (Krura)',
    ),
  ];

  // ═══════════════════════════════════════════════════════════════
  // HOUSES (Bhavas)
  // ═══════════════════════════════════════════════════════════════
  
  static const List<House> houses = [
    House(
      number: 1,
      name: 'First House',
      sanskritName: 'Lagna / Tanu Bhava',
      lifeAreas: [
        'Self & personality',
        'Physical body & health',
        'Overall life direction',
        'First impressions',
        'Vitality & constitution',
      ],
      realWorldExamples: [
        'Your natural appearance and body type',
        'How others perceive you at first meeting',
        'Your general approach to life',
        'Health tendencies and physical constitution',
      ],
      problemManifestations: [
        'Identity confusion or weak sense of self',
        'Chronic health issues',
        'Difficulty making a good first impression',
        'Low vitality or energy',
      ],
      growthOpportunities: [
        'Developing strong self-identity',
        'Improving physical health and appearance',
        'Building confident presence',
        'Aligning actions with authentic self',
      ],
      naturalSign: 'Aries',
      naturalPlanet: 'Sun/Mars',
      description: 'The house of self - your identity, body, and how you begin all things',
    ),
    House(
      number: 2,
      name: 'Second House',
      sanskritName: 'Dhana Bhava',
      lifeAreas: [
        'Wealth & resources',
        'Family & early childhood',
        'Speech & communication',
        'Food & diet',
        'Face & oral health',
      ],
      realWorldExamples: [
        'Your relationship with money and savings',
        'Family values and traditions',
        'Your speaking style and voice',
        'Eating habits and food preferences',
      ],
      problemManifestations: [
        'Financial instability',
        'Difficult family relationships',
        'Speech problems or harsh words',
        'Unhealthy eating patterns',
      ],
      growthOpportunities: [
        'Building financial security',
        'Healing family relationships',
        'Developing eloquent speech',
        'Creating healthy relationship with food',
      ],
      naturalSign: 'Taurus',
      naturalPlanet: 'Venus/Jupiter',
      description: 'The house of resources - what you value, accumulate, and nourish',
    ),
    House(
      number: 3,
      name: 'Third House',
      sanskritName: 'Sahaja Bhava',
      lifeAreas: [
        'Courage & initiative',
        'Siblings & neighbors',
        'Short journeys & communications',
        'Skills & hobbies',
        'Writing & media',
      ],
      realWorldExamples: [
        'Your relationship with siblings',
        'Daily communication patterns',
        'Short trips and local travel',
        'Creative hobbies and skills',
      ],
      problemManifestations: [
        'Lack of courage or initiative',
        'Sibling conflicts',
        'Communication breakdowns',
        'Unfulfilled creative potential',
      ],
      growthOpportunities: [
        'Building courage and confidence',
        'Improving sibling relationships',
        'Developing communication skills',
        'Mastering new skills and hobbies',
      ],
      naturalSign: 'Gemini',
      naturalPlanet: 'Mercury/Mars',
      description: 'The house of effort - your courage, skills, and immediate environment',
    ),
    House(
      number: 4,
      name: 'Fourth House',
      sanskritName: 'Sukha Bhava',
      lifeAreas: [
        'Home & mother',
        'Emotional foundation',
        'Property & vehicles',
        'Education & degrees',
        'Inner peace & happiness',
      ],
      realWorldExamples: [
        'Your home environment and living space',
        'Relationship with mother',
        'Emotional security patterns',
        'Property ownership and vehicles',
      ],
      problemManifestations: [
        'Lack of emotional security',
        'Difficult relationship with mother',
        'Unstable living situations',
        'Deep-seated unhappiness',
      ],
      growthOpportunities: [
        'Creating a peaceful home',
        'Healing maternal relationships',
        'Building emotional resilience',
        'Finding inner contentment',
      ],
      naturalSign: 'Cancer',
      naturalPlanet: 'Moon',
      description: 'The house of happiness - your emotional roots, home, and inner peace',
    ),
    House(
      number: 5,
      name: 'Fifth House',
      sanskritName: 'Putra Bhava',
      lifeAreas: [
        'Creativity & self-expression',
        'Children & progeny',
        'Romance & love affairs',
        'Intelligence & learning',
        'Past life merits',
      ],
      realWorldExamples: [
        'Your creative expressions and projects',
        'Relationship with children',
        'Romantic experiences and dating',
        'Learning style and intelligence',
      ],
      problemManifestations: [
        'Creative blocks',
        'Difficulties with children',
        'Unfulfilling romantic life',
        'Learning challenges',
      ],
      growthOpportunities: [
        'Expressing creativity freely',
        'Nurturing children (own or others)',
        'Finding joy in romance',
        'Developing intellectual abilities',
      ],
      naturalSign: 'Leo',
      naturalPlanet: 'Sun/Jupiter',
      description: 'The house of creation - your creative expression, joy, and what you birth into the world',
    ),
    House(
      number: 6,
      name: 'Sixth House',
      sanskritName: 'Ripu Bhava',
      lifeAreas: [
        'Health & disease',
        'Enemies & obstacles',
        'Service & daily work',
        'Debts & litigation',
        'Pets & small animals',
      ],
      realWorldExamples: [
        'Your daily work routine',
        'Health challenges and wellness practices',
        'How you handle conflicts',
        'Your service orientation',
      ],
      problemManifestations: [
        'Chronic health issues',
        'Workplace conflicts',
        'Debt problems',
        'Constant obstacles and enemies',
      ],
      growthOpportunities: [
        'Developing excellent health habits',
        'Turning enemies into allies',
        'Mastering daily routines',
        'Finding purpose through service',
      ],
      naturalSign: 'Virgo',
      naturalPlanet: 'Mercury/Saturn',
      description: 'The house of obstacles - challenges you must overcome and service you must render',
    ),
    House(
      number: 7,
      name: 'Seventh House',
      sanskritName: 'Kalatra Bhava',
      lifeAreas: [
        'Marriage & partnerships',
        'Business relationships',
        'Public dealings',
        'Open enemies',
        'Foreign travel',
      ],
      realWorldExamples: [
        'Your marriage or committed relationship',
        'Business partnerships',
        'How others experience you',
        'Legal contracts and agreements',
      ],
      problemManifestations: [
        'Marriage difficulties',
        'Partnership conflicts',
        'Public reputation issues',
        'Inability to commit',
      ],
      growthOpportunities: [
        'Building strong partnerships',
        'Developing relationship skills',
        'Learning through others',
        'Finding balance in partnerships',
      ],
      naturalSign: 'Libra',
      naturalPlanet: 'Venus',
      description: 'The house of partnership - your one-to-one relationships and what others mirror back to you',
    ),
    House(
      number: 8,
      name: 'Eighth House',
      sanskritName: 'Ayur Bhava',
      lifeAreas: [
        'Transformation & death',
        'Hidden knowledge & occult',
        'Inheritance & shared resources',
        'Longevity & chronic issues',
        'Research & investigation',
      ],
      realWorldExamples: [
        'Major life transformations',
        'Interest in mysteries and hidden knowledge',
        'Inheritance and spouse\'s resources',
        'Chronic health patterns',
      ],
      problemManifestations: [
        'Fear of change and death',
        'Secrets and hidden issues',
        'Dependency on others\' resources',
        'Chronic health challenges',
      ],
      growthOpportunities: [
        'Embracing transformation',
        'Developing research abilities',
        'Healing through depth work',
        'Mastering hidden knowledge',
      ],
      naturalSign: 'Scorpio',
      naturalPlanet: 'Mars/Saturn',
      description: 'The house of transformation - what must die for you to be reborn',
    ),
    House(
      number: 9,
      name: 'Ninth House',
      sanskritName: 'Dharma Bhava',
      lifeAreas: [
        'Higher learning & philosophy',
        'Father & teachers',
        'Long journeys & foreign lands',
        'Religion & spirituality',
        'Luck & fortune',
      ],
      realWorldExamples: [
        'Your relationship with higher education',
        'Spiritual and philosophical beliefs',
        'Long-distance travel experiences',
        'Relationship with father',
      ],
      problemManifestations: [
        'Lack of meaning or purpose',
        'Difficult relationship with father',
        'Dogmatic beliefs',
        'Unlucky patterns',
      ],
      growthOpportunities: [
        'Finding your life purpose',
        'Developing wisdom and philosophy',
        'Expanding through travel',
        'Building a relationship with the Divine',
      ],
      naturalSign: 'Sagittarius',
      naturalPlanet: 'Jupiter/Sun',
      description: 'The house of dharma - your purpose, beliefs, and what guides your path',
    ),
    House(
      number: 10,
      name: 'Tenth House',
      sanskritName: 'Karma Bhava',
      lifeAreas: [
        'Career & profession',
        'Status & reputation',
        'Authority & government',
        'Public life',
        'Achievements',
      ],
      realWorldExamples: [
        'Your career path and profession',
        'Public reputation and status',
        'Relationship with authorities',
        'Major achievements',
      ],
      problemManifestations: [
        'Career stagnation',
        'Reputation damage',
        'Conflicts with authority',
        'Unfulfilled ambitions',
      ],
      growthOpportunities: [
        'Building meaningful career',
        'Earning respect and reputation',
        'Achieving professional goals',
        'Contributing to society',
      ],
      naturalSign: 'Capricorn',
      naturalPlanet: 'Saturn/Mercury/Sun',
      description: 'The house of karma - your public role, career, and what you achieve in the world',
    ),
    House(
      number: 11,
      name: 'Eleventh House',
      sanskritName: 'Labha Bhava',
      lifeAreas: [
        'Gains & income',
        'Friends & networks',
        'Hopes & wishes',
        'Elder siblings',
        'Social groups',
      ],
      realWorldExamples: [
        'Your income and financial gains',
        'Friend circles and social networks',
        'Your hopes and aspirations',
        'Relationship with elder siblings',
      ],
      problemManifestations: [
        'Financial losses',
        'Unfulfilled wishes',
        'Unhealthy friendships',
        'Isolation from groups',
      ],
      growthOpportunities: [
        'Increasing income streams',
        'Building supportive friendships',
        'Manifesting desires',
        'Contributing to communities',
      ],
      naturalSign: 'Aquarius',
      naturalPlanet: 'Saturn/Jupiter',
      description: 'The house of gains - what you achieve through networks and what fulfills your wishes',
    ),
    House(
      number: 12,
      name: 'Twelfth House',
      sanskritName: 'Vyaya Bhava',
      lifeAreas: [
        'Losses & expenditure',
        'Spirituality & liberation',
        'Foreign residence',
        'Isolation & sleep',
        'Subconscious patterns',
      ],
      realWorldExamples: [
        'Your spending patterns',
        'Sleep and dream life',
        'Meditation and spiritual practices',
        'Foreign connections',
      ],
      problemManifestations: [
        'Excessive spending or losses',
        'Sleep disorders',
        'Feeling lost or disconnected',
        'Hidden self-sabotage',
      ],
      growthOpportunities: [
        'Developing spiritual practices',
        'Making peace with letting go',
        'Understanding subconscious patterns',
        'Finding liberation through surrender',
      ],
      naturalSign: 'Pisces',
      naturalPlanet: 'Jupiter/Ketu',
      description: 'The house of liberation - what you must release and transcend',
    ),
  ];

  // ═══════════════════════════════════════════════════════════════
  // SIGNS (Rashis)
  // ═══════════════════════════════════════════════════════════════
  
  static const List<Sign> signs = [
    Sign(
      id: 'aries',
      name: 'Aries',
      sanskritName: 'Mesha',
      symbol: '♈',
      element: 'Fire',
      modality: 'Cardinal',
      rulingPlanet: 'Mars',
      behavioralStyles: [
        'Direct and assertive communication',
        'Quick decision-making',
        'Pioneering and initiating',
        'Competitive nature',
      ],
      motivationPatterns: [
        'Desire to be first and lead',
        'Need for action and movement',
        'Driven by challenges',
        'Motivated by independence',
      ],
      strengths: [
        'Courage and bravery',
        'Initiative and energy',
        'Leadership abilities',
        'Enthusiasm and passion',
      ],
      blindSpots: [
        'Impatience',
        'Aggression when frustrated',
        'Difficulty finishing what is started',
        'Self-centeredness',
      ],
      description: 'The warrior sign - bold, energetic, and ready to conquer challenges',
      houseNumber: 1,
    ),
    Sign(
      id: 'taurus',
      name: 'Taurus',
      sanskritName: 'Vrishabha',
      symbol: '♉',
      element: 'Earth',
      modality: 'Fixed',
      rulingPlanet: 'Venus',
      behavioralStyles: [
        'Steady and reliable approach',
        'Appreciation for comfort and luxury',
        'Patient and methodical',
        'Sensory-oriented experience',
      ],
      motivationPatterns: [
        'Security and stability',
        'Material comfort',
        'Pleasure and enjoyment',
        'Building lasting value',
      ],
      strengths: [
        'Dependability',
        'Patience and persistence',
        'Practical wisdom',
        'Artistic sensibility',
      ],
      blindSpots: [
        'Stubbornness',
        'Resistance to change',
        'Materialism',
        'Possessiveness',
      ],
      description: 'The builder sign - stable, sensual, and focused on creating lasting value',
      houseNumber: 2,
    ),
    Sign(
      id: 'gemini',
      name: 'Gemini',
      sanskritName: 'Mithuna',
      symbol: '♊',
      element: 'Air',
      modality: 'Mutable',
      rulingPlanet: 'Mercury',
      behavioralStyles: [
        'Versatile and adaptable',
        'Intellectually curious',
        'Communicative and social',
        'Quick-witted and playful',
      ],
      motivationPatterns: [
        'Mental stimulation',
        'Variety and change',
        'Connection through communication',
        'Learning and sharing information',
      ],
      strengths: [
        'Communication skills',
        'Adaptability',
        'Quick learning',
        'Social intelligence',
      ],
      blindSpots: [
        'Superficiality',
        'Inconsistency',
        'Nervousness',
        'Difficulty with commitment',
      ],
      description: 'The communicator sign - curious, versatile, and mentally active',
      houseNumber: 3,
    ),
    Sign(
      id: 'cancer',
      name: 'Cancer',
      sanskritName: 'Karka',
      symbol: '♋',
      element: 'Water',
      modality: 'Cardinal',
      rulingPlanet: 'Moon',
      behavioralStyles: [
        'Nurturing and protective',
        'Emotionally intuitive',
        'Home-centered',
        'Memory-oriented',
      ],
      motivationPatterns: [
        'Emotional security',
        'Family and belonging',
        'Caring for others',
        'Creating safe spaces',
      ],
      strengths: [
        'Emotional intelligence',
        'Nurturing abilities',
        'Intuition',
        'Loyalty to loved ones',
      ],
      blindSpots: [
        'Moodiness',
        'Over-sensitivity',
        'Clinging to the past',
        'Indirect communication',
      ],
      description: 'The nurturer sign - protective, emotional, and deeply caring',
      houseNumber: 4,
    ),
    Sign(
      id: 'leo',
      name: 'Leo',
      sanskritName: 'Simha',
      symbol: '♌',
      element: 'Fire',
      modality: 'Fixed',
      rulingPlanet: 'Sun',
      behavioralStyles: [
        'Confident and charismatic',
        'Creative self-expression',
        'Generous and warm',
        'Dramatic and theatrical',
      ],
      motivationPatterns: [
        'Recognition and appreciation',
        'Creative expression',
        'Leadership opportunities',
        'Being special and unique',
      ],
      strengths: [
        'Confidence',
        'Creativity',
        'Leadership',
        'Generosity',
      ],
      blindSpots: [
        'Pride and ego',
        'Need for constant validation',
        'Dominating tendencies',
        'Difficulty accepting criticism',
      ],
      description: 'The king sign - confident, creative, and seeking recognition',
      houseNumber: 5,
    ),
    Sign(
      id: 'virgo',
      name: 'Virgo',
      sanskritName: 'Kanya',
      symbol: '♍',
      element: 'Earth',
      modality: 'Mutable',
      rulingPlanet: 'Mercury',
      behavioralStyles: [
        'Analytical and detail-oriented',
        'Service-minded',
        'Health-conscious',
        'Perfectionist tendencies',
      ],
      motivationPatterns: [
        'Improvement and refinement',
        'Being useful and helpful',
        'Understanding systems',
        'Creating order from chaos',
      ],
      strengths: [
        'Analytical abilities',
        'Attention to detail',
        'Service orientation',
        'Practical problem-solving',
      ],
      blindSpots: [
        'Over-criticism',
        'Anxiety and worry',
        'Perfectionism',
        'Missing the big picture',
      ],
      description: 'The analyst sign - precise, helpful, and constantly improving',
      houseNumber: 6,
    ),
    Sign(
      id: 'libra',
      name: 'Libra',
      sanskritName: 'Tula',
      symbol: '♎',
      element: 'Air',
      modality: 'Cardinal',
      rulingPlanet: 'Venus',
      behavioralStyles: [
        'Diplomatic and balanced',
        'Partnership-oriented',
        'Aesthetically aware',
        'Justice-seeking',
      ],
      motivationPatterns: [
        'Harmony in relationships',
        'Fairness and justice',
        'Beauty and refinement',
        'Social connection',
      ],
      strengths: [
        'Diplomacy',
        'Fairness',
        'Aesthetic sense',
        'Relationship skills',
      ],
      blindSpots: [
        'Indecisiveness',
        'People-pleasing',
        'Avoiding conflict',
        'Dependency on others\' opinions',
      ],
      description: 'The diplomat sign - balanced, fair, and seeking harmony',
      houseNumber: 7,
    ),
    Sign(
      id: 'scorpio',
      name: 'Scorpio',
      sanskritName: 'Vrishchika',
      symbol: '♏',
      element: 'Water',
      modality: 'Fixed',
      rulingPlanet: 'Mars',
      behavioralStyles: [
        'Intense and penetrating',
        'Secretive and private',
        'Transformative approach',
        'All-or-nothing commitment',
      ],
      motivationPatterns: [
        'Deep understanding and truth',
        'Power and control',
        'Transformation and rebirth',
        'Emotional intimacy',
      ],
      strengths: [
        'Emotional depth',
        'Research abilities',
        'Determination',
        'Transformative power',
      ],
      blindSpots: [
        'Jealousy and possessiveness',
        'Manipulation',
        'Holding grudges',
        'Excessive secrecy',
      ],
      description: 'The transformer sign - intense, deep, and capable of profound change',
      houseNumber: 8,
    ),
    Sign(
      id: 'sagittarius',
      name: 'Sagittarius',
      sanskritName: 'Dhanu',
      symbol: '♐',
      element: 'Fire',
      modality: 'Mutable',
      rulingPlanet: 'Jupiter',
      behavioralStyles: [
        'Optimistic and enthusiastic',
        'Freedom-loving',
        'Philosophical and expansive',
        'Direct and honest',
      ],
      motivationPatterns: [
        'Search for meaning and truth',
        'Adventure and exploration',
        'Freedom and independence',
        'Growth and expansion',
      ],
      strengths: [
        'Optimism',
        'Wisdom-seeking',
        'Honesty',
        'Inspirational quality',
      ],
      blindSpots: [
        'Over-promising',
        'Tactlessness',
        'Restlessness',
        'Dogmatism',
      ],
      description: 'The philosopher sign - optimistic, adventurous, and truth-seeking',
      houseNumber: 9,
    ),
    Sign(
      id: 'capricorn',
      name: 'Capricorn',
      sanskritName: 'Makara',
      symbol: '♑',
      element: 'Earth',
      modality: 'Cardinal',
      rulingPlanet: 'Saturn',
      behavioralStyles: [
        'Ambitious and goal-oriented',
        'Disciplined and responsible',
        'Traditional and conservative',
        'Strategic and practical',
      ],
      motivationPatterns: [
        'Achievement and success',
        'Building lasting structures',
        'Respect and authority',
        'Long-term security',
      ],
      strengths: [
        'Discipline',
        'Ambition',
        'Responsibility',
        'Strategic thinking',
      ],
      blindSpots: [
        'Workaholism',
        'Pessimism',
        'Rigidity',
        'Emotional coldness',
      ],
      description: 'The achiever sign - disciplined, ambitious, and building for the future',
      houseNumber: 10,
    ),
    Sign(
      id: 'aquarius',
      name: 'Aquarius',
      sanskritName: 'Kumbha',
      symbol: '♒',
      element: 'Air',
      modality: 'Fixed',
      rulingPlanet: 'Saturn',
      behavioralStyles: [
        'Independent and unconventional',
        'Humanitarian and progressive',
        'Intellectual and detached',
        'Group-oriented',
      ],
      motivationPatterns: [
        'Innovation and progress',
        'Social causes and humanity',
        'Intellectual freedom',
        'Being unique and original',
      ],
      strengths: [
        'Originality',
        'Humanitarian vision',
        'Intellectual objectivity',
        'Progressive thinking',
      ],
      blindSpots: [
        'Emotional detachment',
        'Stubbornness in ideas',
        'Rebellion for rebellion\'s sake',
        'Aloofness',
      ],
      description: 'The innovator sign - original, humanitarian, and forward-thinking',
      houseNumber: 11,
    ),
    Sign(
      id: 'pisces',
      name: 'Pisces',
      sanskritName: 'Meena',
      symbol: '♓',
      element: 'Water',
      modality: 'Mutable',
      rulingPlanet: 'Jupiter',
      behavioralStyles: [
        'Intuitive and empathic',
        'Creative and imaginative',
        'Compassionate and selfless',
        'Dreamy and escapist',
      ],
      motivationPatterns: [
        'Spiritual connection',
        'Creative expression',
        'Helping and healing others',
        'Transcending ordinary reality',
      ],
      strengths: [
        'Intuition',
        'Compassion',
        'Artistic creativity',
        'Spiritual awareness',
      ],
      blindSpots: [
        'Escapism',
        'Victim mentality',
        'Lack of boundaries',
        'Confusion',
      ],
      description: 'The mystic sign - intuitive, compassionate, and seeking transcendence',
      houseNumber: 12,
    ),
  ];

  // Helper methods
  static Planet? getPlanetById(String id) {
    try {
      return planets.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }

  static House? getHouseByNumber(int number) {
    try {
      return houses.firstWhere((h) => h.number == number);
    } catch (_) {
      return null;
    }
  }

  static Sign? getSignById(String id) {
    try {
      return signs.firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }
}
