import '../models/models.dart';

/// Complete Nakshatra data for all 27 lunar mansions
/// Each nakshatra has 10+ syllables for comprehensive name matching
/// Supports: first syllable analysis, dominant sound, ending sound patterns
class NakshatraData {
  static const List<Nakshatra> nakshatras = [
    Nakshatra(
      number: 1,
      name: 'Ashwini',
      lord: 'Ketu',
      deity: 'Ashwini Kumaras',
      symbol: 'Horse Head',
      syllables: ['Chu', 'Che', 'Cho', 'La', 'Cha', 'Kha', 'Ja', 'Sha', 'Tha', 'Choo'],
      signSpan: 'Aries 0° - 13°20\'',
      psychologicalDrivers: [
        'Need for speed and quick results',
        'Desire to heal and help others',
        'Independent spirit',
      ],
      unconsciousBehaviors: [
        'Rushing into decisions',
        'Impatience with slow processes',
        'Taking initiative without consultation',
      ],
      strengtheningPractices: [
        'Practice patience in daily tasks',
        'Learn healing modalities',
        'Channel speed into productive goals',
      ],
      nature: 'Light/Swift',
      gana: 'Dev',
      animal: 'Horse',
      description: 'The star of transport - swift healing and new beginnings',
    ),
    Nakshatra(
      number: 2,
      name: 'Bharani',
      lord: 'Venus',
      deity: 'Yama',
      symbol: 'Yoni (Female Organ)',
      syllables: ['Li', 'Lu', 'Le', 'Lo', 'La', 'Na', 'Bha', 'Ra', 'Va', 'Dha', 'Lee'],
      signSpan: 'Aries 13°20\' - 26°40\'',
      psychologicalDrivers: [
        'Need to nurture and create',
        'Strong sense of responsibility',
        'Understanding of life cycles',
      ],
      unconsciousBehaviors: [
        'Carrying burdens of others',
        'Intense emotional responses',
        'Struggles with letting go',
      ],
      strengtheningPractices: [
        'Creative arts and expression',
        'Practice healthy boundaries',
        'Understand transformation cycles',
      ],
      nature: 'Fierce/Severe',
      gana: 'Human',
      animal: 'Elephant',
      description: 'The star of restraint - bearing life\'s responsibilities',
    ),
    Nakshatra(
      number: 3,
      name: 'Krittika',
      lord: 'Sun',
      deity: 'Agni',
      symbol: 'Razor/Flame',
      syllables: ['A', 'E', 'U', 'Ai', 'O', 'Ka', 'Kha', 'Ga', 'Gha', 'Sa', 'Aa'],
      signSpan: 'Aries 26°40\' - Taurus 10°',
      psychologicalDrivers: [
        'Need for purification and truth',
        'Strong willpower and determination',
        'Desire to cut through illusions',
      ],
      unconsciousBehaviors: [
        'Being overly critical',
        'Burning bridges unnecessarily',
        'Harsh speech when frustrated',
      ],
      strengtheningPractices: [
        'Practice constructive criticism',
        'Cultivate warmth along with truth',
        'Channel fire into creative pursuits',
      ],
      nature: 'Mixed',
      gana: 'Rakshasa',
      animal: 'Goat',
      description: 'The star of fire - cutting through to truth',
    ),
    Nakshatra(
      number: 4,
      name: 'Rohini',
      lord: 'Moon',
      deity: 'Brahma',
      symbol: 'Cart/Chariot',
      syllables: ['O', 'Va', 'Vi', 'Vu', 'Ve', 'Vo', 'Ba', 'Bha', 'Ma', 'Pa'],
      signSpan: 'Taurus 10° - 23°20\'',
      psychologicalDrivers: [
        'Need for beauty and pleasure',
        'Strong creative urges',
        'Desire for growth and fertility',
      ],
      unconsciousBehaviors: [
        'Attachment to material comforts',
        'Possessiveness in relationships',
        'Indulgence in sensory pleasures',
      ],
      strengtheningPractices: [
        'Channel creativity productively',
        'Practice non-attachment',
        'Develop inner beauty alongside outer',
      ],
      nature: 'Fixed',
      gana: 'Human',
      animal: 'Serpent',
      description: 'The star of ascent - growth, beauty, and creativity',
    ),
    Nakshatra(
      number: 5,
      name: 'Mrigashira',
      lord: 'Mars',
      deity: 'Soma',
      symbol: 'Deer Head',
      syllables: ['Ve', 'Vo', 'Ka', 'Ki', 'Ku', 'Gh', 'Ch', 'Sa', 'Da', 'Tha', 'Vee'],
      signSpan: 'Taurus 23°20\' - Gemini 6°40\'',
      psychologicalDrivers: [
        'Endless curiosity and searching',
        'Need for variety and exploration',
        'Gentle yet restless nature',
      ],
      unconsciousBehaviors: [
        'Never being satisfied',
        'Constant seeking without finding',
        'Difficulty committing to one path',
      ],
      strengtheningPractices: [
        'Focus curiosity on depth over breadth',
        'Practice contentment exercises',
        'Channel searching into spiritual growth',
      ],
      nature: 'Soft/Tender',
      gana: 'Dev',
      animal: 'Serpent',
      description: 'The star of searching - eternal quest for fulfillment',
    ),
    Nakshatra(
      number: 6,
      name: 'Ardra',
      lord: 'Rahu',
      deity: 'Rudra',
      symbol: 'Teardrop/Diamond',
      syllables: ['Ku', 'Gha', 'Na', 'Cha', 'Ta', 'Sa', 'Ra', 'Da', 'Ha', 'La', 'Koo'],
      signSpan: 'Gemini 6°40\' - 20°',
      psychologicalDrivers: [
        'Need for transformation through struggle',
        'Deep emotional processing',
        'Desire to understand suffering',
      ],
      unconsciousBehaviors: [
        'Creating storms for growth',
        'Intense emotional outbursts',
        'Difficulty with easy paths',
      ],
      strengtheningPractices: [
        'Channel intensity into research',
        'Practice emotional regulation',
        'Use storms for creative destruction',
      ],
      nature: 'Sharp/Dreadful',
      gana: 'Human',
      animal: 'Dog',
      description: 'The star of sorrow - transformation through tears',
    ),
    Nakshatra(
      number: 7,
      name: 'Punarvasu',
      lord: 'Jupiter',
      deity: 'Aditi',
      symbol: 'Bow and Quiver',
      syllables: ['Ke', 'Ko', 'Ha', 'Hi', 'He', 'Ho', 'Ra', 'Re', 'La', 'Pa', 'Kee'],
      signSpan: 'Gemini 20° - Cancer 3°20\'',
      psychologicalDrivers: [
        'Need for renewal and return',
        'Optimistic worldview',
        'Desire for safety and home',
      ],
      unconsciousBehaviors: [
        'Returning to old patterns',
        'Over-optimism ignoring reality',
        'Difficulty with permanent change',
      ],
      strengtheningPractices: [
        'Build on past successes consciously',
        'Balance optimism with realism',
        'Create stable home base',
      ],
      nature: 'Moveable',
      gana: 'Dev',
      animal: 'Cat',
      description: 'The star of renewal - returning to goodness',
    ),
    Nakshatra(
      number: 8,
      name: 'Pushya',
      lord: 'Saturn',
      deity: 'Brihaspati',
      symbol: 'Cow Udder/Lotus',
      syllables: ['Hu', 'He', 'Ho', 'Da', 'Di', 'Du', 'De', 'Do', 'Na', 'Pa', 'Hoo'],
      signSpan: 'Cancer 3°20\' - 16°40\'',
      psychologicalDrivers: [
        'Need to nourish and be nourished',
        'Strong sense of dharma',
        'Desire to support and sustain',
      ],
      unconsciousBehaviors: [
        'Over-giving to the point of depletion',
        'Difficulty receiving help',
        'Taking on parental roles inappropriately',
      ],
      strengtheningPractices: [
        'Practice receiving as well as giving',
        'Set healthy nourishment boundaries',
        'Develop sustainable giving practices',
      ],
      nature: 'Light',
      gana: 'Dev',
      animal: 'Goat',
      description: 'The star of nourishment - the most auspicious nakshatra',
    ),
    Nakshatra(
      number: 9,
      name: 'Ashlesha',
      lord: 'Mercury',
      deity: 'Nagas',
      symbol: 'Coiled Serpent',
      syllables: ['Di', 'Du', 'De', 'Do', 'Ti', 'Tu', 'Te', 'To', 'Na', 'Cha', 'Dee'],
      signSpan: 'Cancer 16°40\' - 30°',
      psychologicalDrivers: [
        'Need for deep understanding',
        'Kundalini and transformative energy',
        'Desire to penetrate mysteries',
      ],
      unconsciousBehaviors: [
        'Manipulative tendencies',
        'Holding onto grudges',
        'Secretive behavior',
      ],
      strengtheningPractices: [
        'Use perception for healing not harm',
        'Practice transparency',
        'Channel intensity into spiritual growth',
      ],
      nature: 'Sharp',
      gana: 'Rakshasa',
      animal: 'Cat',
      description: 'The star of embrace - kundalini and serpent wisdom',
    ),
    Nakshatra(
      number: 10,
      name: 'Magha',
      lord: 'Ketu',
      deity: 'Pitris (Ancestors)',
      symbol: 'Royal Throne',
      syllables: ['Ma', 'Mi', 'Mu', 'Me', 'Mo', 'Ra', 'Ri', 'Ru', 'Re', 'Ta', 'Maa'],
      signSpan: 'Leo 0° - 13°20\'',
      psychologicalDrivers: [
        'Need for respect and authority',
        'Connection to lineage and ancestry',
        'Desire for recognition',
      ],
      unconsciousBehaviors: [
        'Expecting royal treatment',
        'Difficulty with humble roles',
        'Past-focused thinking',
      ],
      strengtheningPractices: [
        'Honor ancestors consciously',
        'Balance pride with humility',
        'Use authority to serve others',
      ],
      nature: 'Fierce',
      gana: 'Rakshasa',
      animal: 'Rat',
      description: 'The star of power - royal lineage and authority',
    ),
    Nakshatra(
      number: 11,
      name: 'Purva Phalguni',
      lord: 'Venus',
      deity: 'Bhaga',
      symbol: 'Hammock/Front legs of bed',
      syllables: ['Mo', 'Ta', 'Ti', 'Tu', 'Te', 'Pa', 'Pi', 'Pu', 'Pe', 'La', 'Moo'],
      signSpan: 'Leo 13°20\' - 26°40\'',
      psychologicalDrivers: [
        'Need for pleasure and enjoyment',
        'Creative and romantic nature',
        'Desire for relaxation and luxury',
      ],
      unconsciousBehaviors: [
        'Overindulgence in pleasures',
        'Laziness when comfortable',
        'Vanity and self-focus',
      ],
      strengtheningPractices: [
        'Balance enjoyment with productivity',
        'Use creativity for higher purposes',
        'Practice gratitude for pleasures',
      ],
      nature: 'Fierce',
      gana: 'Human',
      animal: 'Rat',
      description: 'The star of rest - pleasure and creative enjoyment',
    ),
    Nakshatra(
      number: 12,
      name: 'Uttara Phalguni',
      lord: 'Sun',
      deity: 'Aryaman',
      symbol: 'Bed/Back legs of bed',
      syllables: ['Te', 'To', 'Pa', 'Pi', 'Pu', 'Sha', 'Na', 'Ha', 'La', 'Ma', 'Tee'],
      signSpan: 'Leo 26°40\' - Virgo 10°',
      psychologicalDrivers: [
        'Need for lasting partnerships',
        'Strong sense of duty and loyalty',
        'Desire for permanent unions',
      ],
      unconsciousBehaviors: [
        'Over-focus on partnerships',
        'Difficulty being alone',
        'Patronizing behavior',
      ],
      strengtheningPractices: [
        'Develop individual identity',
        'Practice healthy independence',
        'Use patronage to uplift others',
      ],
      nature: 'Fixed',
      gana: 'Human',
      animal: 'Cow',
      description: 'The star of patronage - lasting unions and support',
    ),
    Nakshatra(
      number: 13,
      name: 'Hasta',
      lord: 'Moon',
      deity: 'Savitar',
      symbol: 'Hand/Fist',
      syllables: ['Pu', 'Sha', 'Na', 'Tha', 'Ra', 'Ta', 'Pa', 'Ma', 'La', 'Ka', 'Poo'],
      signSpan: 'Virgo 10° - 23°20\'',
      psychologicalDrivers: [
        'Need for skill and dexterity',
        'Strong healing abilities',
        'Desire to create with hands',
      ],
      unconsciousBehaviors: [
        'Manipulating situations cleverly',
        'Overworking with hands',
        'Restless hand movements',
      ],
      strengtheningPractices: [
        'Develop craftsmanship',
        'Use hands for healing work',
        'Practice mindful hand activities',
      ],
      nature: 'Light',
      gana: 'Dev',
      animal: 'Buffalo',
      description: 'The star of the hand - skill, craft, and healing touch',
    ),
    Nakshatra(
      number: 14,
      name: 'Chitra',
      lord: 'Mars',
      deity: 'Tvashtar',
      symbol: 'Bright Jewel/Pearl',
      syllables: ['Pe', 'Po', 'Ra', 'Ri', 'Ru', 'Re', 'Ta', 'Na', 'Ma', 'La', 'Pee'],
      signSpan: 'Virgo 23°20\' - Libra 6°40\'',
      psychologicalDrivers: [
        'Need for beauty and perfection',
        'Strong creative and artistic drive',
        'Desire to create lasting works',
      ],
      unconsciousBehaviors: [
        'Obsession with appearances',
        'Never satisfied with creations',
        'Superficial assessments',
      ],
      strengtheningPractices: [
        'Create art and beauty',
        'Appreciate inner beauty',
        'Use creativity for transformation',
      ],
      nature: 'Soft',
      gana: 'Rakshasa',
      animal: 'Tiger',
      description: 'The star of opportunity - brilliant creative expression',
    ),
    Nakshatra(
      number: 15,
      name: 'Swati',
      lord: 'Rahu',
      deity: 'Vayu',
      symbol: 'Coral/Sword',
      syllables: ['Ru', 'Re', 'Ro', 'Ta', 'Ti', 'Tu', 'Te', 'Pa', 'Na', 'La', 'Roo'],
      signSpan: 'Libra 6°40\' - 20°',
      psychologicalDrivers: [
        'Need for independence and freedom',
        'Flexible and adaptable nature',
        'Desire for self-determination',
      ],
      unconsciousBehaviors: [
        'Scattered by every wind',
        'Difficulty with commitment',
        'Restless and unsettled',
      ],
      strengtheningPractices: [
        'Develop inner stability',
        'Channel flexibility productively',
        'Practice grounded independence',
      ],
      nature: 'Moveable',
      gana: 'Dev',
      animal: 'Buffalo',
      description: 'The star of the wind - independence and flexibility',
    ),
    Nakshatra(
      number: 16,
      name: 'Vishakha',
      lord: 'Jupiter',
      deity: 'Indra-Agni',
      symbol: 'Triumphal Arch/Potter\'s Wheel',
      syllables: ['Ti', 'Tu', 'Te', 'To', 'Na', 'Ni', 'Nu', 'Ne', 'La', 'Ra', 'Tee'],
      signSpan: 'Libra 20° - Scorpio 3°20\'',
      psychologicalDrivers: [
        'Single-pointed focus on goals',
        'Strong determination',
        'Need for achievement and success',
      ],
      unconsciousBehaviors: [
        'Obsessive goal pursuit',
        'Ignoring relationships for goals',
        'Never satisfied with achievements',
      ],
      strengtheningPractices: [
        'Balance goals with relationships',
        'Celebrate achievements',
        'Use determination for higher purposes',
      ],
      nature: 'Mixed',
      gana: 'Rakshasa',
      animal: 'Tiger',
      description: 'The star of purpose - single-pointed determination',
    ),
    Nakshatra(
      number: 17,
      name: 'Anuradha',
      lord: 'Saturn',
      deity: 'Mitra',
      symbol: 'Lotus/Triumphal Arch',
      syllables: ['Na', 'Ni', 'Nu', 'Ne', 'No', 'Ma', 'Mi', 'Mu', 'Me', 'Ta', 'Naa'],
      signSpan: 'Scorpio 3°20\' - 16°40\'',
      psychologicalDrivers: [
        'Need for deep friendships',
        'Devotion and loyalty',
        'Ability to bloom in darkness',
      ],
      unconsciousBehaviors: [
        'Over-dependence on friendships',
        'Difficulty setting boundaries',
        'Excessive devotion',
      ],
      strengtheningPractices: [
        'Cultivate healthy friendships',
        'Practice devotion with boundaries',
        'Develop inner resilience',
      ],
      nature: 'Soft',
      gana: 'Dev',
      animal: 'Deer',
      description: 'The star of devotion - friendship and loyalty',
    ),
    Nakshatra(
      number: 18,
      name: 'Jyeshtha',
      lord: 'Mercury',
      deity: 'Indra',
      symbol: 'Circular Amulet/Earring',
      syllables: ['No', 'Ya', 'Yi', 'Yu', 'Ye', 'Ra', 'Ri', 'Ru', 'Re', 'Da', 'Noo'],
      signSpan: 'Scorpio 16°40\' - 30°',
      psychologicalDrivers: [
        'Need for respect and seniority',
        'Protective of family and tribe',
        'Leadership through experience',
      ],
      unconsciousBehaviors: [
        'Arrogance about position',
        'Jealousy of others\' success',
        'Over-protective behavior',
      ],
      strengtheningPractices: [
        'Lead with humility',
        'Mentor younger ones',
        'Use seniority to protect wisely',
      ],
      nature: 'Sharp',
      gana: 'Rakshasa',
      animal: 'Deer',
      description: 'The star of the chief - seniority and protection',
    ),
    Nakshatra(
      number: 19,
      name: 'Mula',
      lord: 'Ketu',
      deity: 'Nirriti',
      symbol: 'Roots/Tied Bunch',
      syllables: ['Ye', 'Yo', 'Bha', 'Bhi', 'Bhu', 'Dha', 'Na', 'Ma', 'La', 'Yee'],
      signSpan: 'Sagittarius 0° - 13°20\'',
      psychologicalDrivers: [
        'Need to get to the root of things',
        'Deep investigative nature',
        'Desire for fundamental transformation',
      ],
      unconsciousBehaviors: [
        'Uprooting stability',
        'Destructive before constructive',
        'Extreme positions',
      ],
      strengtheningPractices: [
        'Use investigation for healing',
        'Build after understanding roots',
        'Channel intensity into research',
      ],
      nature: 'Sharp',
      gana: 'Rakshasa',
      animal: 'Dog',
      description: 'The star of the root - getting to the foundation',
    ),
    Nakshatra(
      number: 20,
      name: 'Purva Ashadha',
      lord: 'Venus',
      deity: 'Apas (Waters)',
      symbol: 'Elephant Tusk/Fan',
      syllables: ['Bhu', 'Dha', 'Pha', 'Ma', 'La', 'Na', 'Ta', 'Ka', 'Bha', 'Boo'],
      signSpan: 'Sagittarius 13°20\' - 26°40\'',
      psychologicalDrivers: [
        'Need for victory and success',
        'Invincible spirit',
        'Desire for purification',
      ],
      unconsciousBehaviors: [
        'Overconfidence in abilities',
        'Declaring victory too soon',
        'Underestimating challenges',
      ],
      strengtheningPractices: [
        'Balance confidence with preparation',
        'Use water for purification rituals',
        'Cultivate sustainable victories',
      ],
      nature: 'Fierce',
      gana: 'Human',
      animal: 'Monkey',
      description: 'The star of invincibility - early victory',
    ),
    Nakshatra(
      number: 21,
      name: 'Uttara Ashadha',
      lord: 'Sun',
      deity: 'Vishvadevas',
      symbol: 'Elephant Tusk/Small Bed',
      syllables: ['Bhe', 'Bho', 'Ja', 'Ji', 'Ju', 'Je', 'Na', 'Pa', 'Ra', 'Bee'],
      signSpan: 'Sagittarius 26°40\' - Capricorn 10°',
      psychologicalDrivers: [
        'Need for permanent victory',
        'Universal approach to life',
        'Desire for lasting achievement',
      ],
      unconsciousBehaviors: [
        'Expecting permanent success',
        'Difficulty with small victories',
        'Overextending for universal goals',
      ],
      strengtheningPractices: [
        'Build lasting foundations',
        'Practice universal compassion',
        'Celebrate incremental progress',
      ],
      nature: 'Fixed',
      gana: 'Human',
      animal: 'Mongoose',
      description: 'The star of final victory - permanent achievement',
    ),
    Nakshatra(
      number: 22,
      name: 'Shravana',
      lord: 'Moon',
      deity: 'Vishnu',
      symbol: 'Ear/Three Footprints',
      syllables: ['Ju', 'Je', 'Jo', 'Gha', 'Da', 'Di', 'Du', 'Na', 'Ma', 'Joo'],
      signSpan: 'Capricorn 10° - 23°20\'',
      psychologicalDrivers: [
        'Need to listen and learn',
        'Strong preservation instinct',
        'Desire for connection through hearing',
      ],
      unconsciousBehaviors: [
        'Gossip and listening to rumors',
        'Passive reception without action',
        'Over-reliance on others\' words',
      ],
      strengtheningPractices: [
        'Practice deep listening',
        'Learn through sacred sounds',
        'Preserve and share wisdom',
      ],
      nature: 'Moveable',
      gana: 'Dev',
      animal: 'Monkey',
      description: 'The star of learning - listening and preservation',
    ),
    Nakshatra(
      number: 23,
      name: 'Dhanishta',
      lord: 'Mars',
      deity: 'Vasus',
      symbol: 'Drum/Flute',
      syllables: ['Ga', 'Gi', 'Gu', 'Ge', 'Go', 'Sa', 'Si', 'Su', 'Na', 'Gaa'],
      signSpan: 'Capricorn 23°20\' - Aquarius 6°40\'',
      psychologicalDrivers: [
        'Need for rhythm and music',
        'Wealth and prosperity drive',
        'Desire for recognition',
      ],
      unconsciousBehaviors: [
        'Obsession with wealth',
        'Showing off achievements',
        'Difficulty sharing resources',
      ],
      strengtheningPractices: [
        'Use music for healing',
        'Practice generous wealth sharing',
        'Find rhythm in daily life',
      ],
      nature: 'Moveable',
      gana: 'Rakshasa',
      animal: 'Lion',
      description: 'The star of symphony - wealth and rhythm',
    ),
    Nakshatra(
      number: 24,
      name: 'Shatabhisha',
      lord: 'Rahu',
      deity: 'Varuna',
      symbol: 'Empty Circle/100 Physicians',
      syllables: ['Go', 'Sa', 'Si', 'Su', 'Se', 'So', 'Da', 'Di', 'Na', 'Goo'],
      signSpan: 'Aquarius 6°40\' - 20°',
      psychologicalDrivers: [
        'Need for healing and service',
        'Secretive and mysterious nature',
        'Desire for truth and purity',
      ],
      unconsciousBehaviors: [
        'Excessive secrecy',
        'Isolation from others',
        'Harsh truth-telling',
      ],
      strengtheningPractices: [
        'Practice healing arts',
        'Balance solitude with connection',
        'Use secrecy for protection not harm',
      ],
      nature: 'Moveable',
      gana: 'Rakshasa',
      animal: 'Horse',
      description: 'The star of healing - hundred physicians',
    ),
    Nakshatra(
      number: 25,
      name: 'Purva Bhadrapada',
      lord: 'Jupiter',
      deity: 'Aja Ekapada',
      symbol: 'Sword/Front of Funeral Cot',
      syllables: ['Se', 'So', 'Da', 'Di', 'Du', 'Na', 'Ma', 'Ta', 'Ka', 'See'],
      signSpan: 'Aquarius 20° - Pisces 3°20\'',
      psychologicalDrivers: [
        'Need for spiritual transformation',
        'Intense and fiery nature',
        'Desire for liberation',
      ],
      unconsciousBehaviors: [
        'Extreme approaches to spirituality',
        'Burning bridges',
        'Intensity that scares others',
      ],
      strengtheningPractices: [
        'Channel intensity into practice',
        'Balance fire with compassion',
        'Use transformation for service',
      ],
      nature: 'Fierce',
      gana: 'Human',
      animal: 'Lion',
      description: 'The star of fire - burning for liberation',
    ),
    Nakshatra(
      number: 26,
      name: 'Uttara Bhadrapada',
      lord: 'Saturn',
      deity: 'Ahir Budhnya',
      symbol: 'Back of Funeral Cot/Twins',
      syllables: ['Du', 'Tha', 'Jha', 'Na', 'Ma', 'Pa', 'La', 'Ra', 'Jna', 'Doo'],
      signSpan: 'Pisces 3°20\' - 16°40\'',
      psychologicalDrivers: [
        'Need for deep wisdom',
        'Controlled and steady nature',
        'Desire for spiritual depth',
      ],
      unconsciousBehaviors: [
        'Excessive renunciation',
        'Coldness in relationships',
        'Over-control of emotions',
      ],
      strengtheningPractices: [
        'Practice steady meditation',
        'Balance discipline with warmth',
        'Use depth for teaching',
      ],
      nature: 'Fixed',
      gana: 'Human',
      animal: 'Cow',
      description: 'The star of the deep - controlled spiritual power',
    ),
    Nakshatra(
      number: 27,
      name: 'Revati',
      lord: 'Mercury',
      deity: 'Pushan',
      symbol: 'Fish/Drum',
      syllables: ['De', 'Do', 'Cha', 'Chi', 'Ta', 'Na', 'Ma', 'La', 'Cho', 'Dee'],
      signSpan: 'Pisces 16°40\' - 30°',
      psychologicalDrivers: [
        'Need to guide and protect',
        'Nurturing of journeys',
        'Desire for safe passages',
      ],
      unconsciousBehaviors: [
        'Over-protection of others',
        'Difficulty with endings',
        'Taking on others\' journeys',
      ],
      strengtheningPractices: [
        'Guide without controlling',
        'Practice healthy closure',
        'Trust others\' paths',
      ],
      nature: 'Soft',
      gana: 'Dev',
      animal: 'Elephant',
      description: 'The star of the journey - safe passage and nourishment',
    ),
  ];

  static Nakshatra? getNakshatraByNumber(int number) {
    try {
      return nakshatras.firstWhere((n) => n.number == number);
    } catch (_) {
      return null;
    }
  }

  static Nakshatra? getNakshatraByName(String name) {
    try {
      return nakshatras.firstWhere(
        (n) => n.name.toLowerCase() == name.toLowerCase(),
      );
    } catch (_) {
      return null;
    }
  }
}
